[tool.black]
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | build
    | conda.recipe
    | dist
    | htmlcov
    | source
)/
'''
